apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 5432
          env:
            # 1. Pulling the Username from the ConfigMap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: node-api-config
                  key: DB_USER

            # 2. Pulling the Database Name from the ConfigMap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: node-api-config
                  key: DB_NAME

            # 3. Pulling the Password from the Secret (Stays hidden!)
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: node-api-secrets
                  key: DB_PASSWORD

            # Tell Postgres to put its internal data inside the mounted folder
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-in-mem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api-in-mem
  template:
    metadata:
      labels:
        app: node-api-in-mem
    spec:
      containers:
        - name: node-api-in-mem
          image: shivansh760/node-api:0b7aae29ed4bcddc3c29cdf95aad34a4e43a0cab
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: node-api-config
            - secretRef:
                name: node-api-secrets
