apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-in-mem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api-in-mem
  template:
    metadata:
      labels:
        app: node-api-in-mem
    spec:
      containers:
        - name: node-api-in-mem
          image: <Image>
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: node-api-config
